name: myActions

on: 
  push:           
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest   

    steps:
      - name: Install the software
        run: sudo apt-get install openjdk-17-jdk

        #uses: actions/setup-java@v3
        #with:
        #  java-version: '17'
        #  distribution: 'temurin'
          
      - name: Clone the project
        run: git clone https://github.com/${{ github.repository }} . 
        #uses: actions/checkout@v3

      - name: Download dependencies
        run: mvn dependency:resolve

      - name: Build project
        run: mvn package

      - name: Run tests
        run: mvn test
