name: myActions

on: 
  push:           
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest   

    steps:
      - name: Install the software
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Clone the project
        uses: actions/checkout@v3

      - name: Download dependencies
        run: mvn dependency:resolve

      - name: Build project
        run: mvn package

      - name: Run tests
        run: mvn test
